modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="opmod"
version="1.0.0"
displayName="Op Mod Renewd"
credits="This is the mod with OpTools. The previous version cant be downloaded. This mod is for my friends."
displayURL="https://dedouwe.nl"
authors="de_douwe"

[[dependencies.opmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




