modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="opmod"
version="1.0.0"
displayName="Op Mod Renewd"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="lucwe, MCreator"

[[dependencies.opmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




